---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  API_PORT: "8000"
  CUSTOM_MESSAGE: {{ .Values.configmap.data.CUSTOM_MESSAGE }}