---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
  - name: backend
    protocol: TCP
    port: 8000
    targetPort: 8000